# **Question 1**

In [70]:
import numpy as np
arr = np.random.randint(1,51, size=(5,4))
print(arr)

[[33 14 45 46]
 [22 15 29 10]
 [ 7  7 11 29]
 [31 29  9 34]
 [21  4 44 40]]


Anti diagonal

In [71]:
anti = [arr[i][-(i+1)] for i in range(min(arr.shape))]
print(anti)

[np.int64(46), np.int64(29), np.int64(7), np.int64(31)]


Maximum

In [72]:
Rmax = np.max(arr, axis=1)
print(Rmax)

[46 29 29 34 44]


elements <= overall mean

In [73]:
Overall_mean = np.mean(arr)
lessThanMean = arr[arr <= Overall_mean]
print(lessThanMean)

[14 22 15 10  7  7 11  9 21  4]


Boundary transversal

In [74]:
def numpy_boundary_traversal(matrix):
  top = list(matrix[0])
  right = [row[-1] for row in matrix[1:-1]]
  bottom = list(matrix[-1][::-1])
  left = [row[0] for row in matrix[-2:0:-1]]
  return top + right + bottom + left
print(numpy_boundary_traversal(arr))

[np.int64(33), np.int64(14), np.int64(45), np.int64(46), np.int64(10), np.int64(29), np.int64(34), np.int64(40), np.int64(44), np.int64(4), np.int64(21), np.int64(31), np.int64(7), np.int64(22)]


# **Question 2**

In [75]:
import numpy as np
arr2 = np.random.uniform(0,10, 20)
print(arr2)
rounded = np.round(arr2,2)
print('rounded : ',rounded)

[1.61131403 0.41069483 0.74231886 8.59549313 4.86118472 1.66193683
 6.75456028 7.1585201  6.02922988 3.3028348  2.89955965 5.40988005
 5.0752666  9.97944996 4.1617269  4.58594005 8.76793348 9.71102886
 6.43107438 5.82962863]
rounded :  [1.61 0.41 0.74 8.6  4.86 1.66 6.75 7.16 6.03 3.3  2.9  5.41 5.08 9.98
 4.16 4.59 8.77 9.71 6.43 5.83]


min, max, median

In [76]:
Amin = np.min(rounded)
Amax = np.max(rounded)
Amedian = np.median(rounded)
print('min: ', Amin,'max:', Amax,'median: ', Amedian)


min:  0.41 max: 9.98 median:  5.245


lees than 5 with squares

In [77]:
arr_less = np.where(rounded < 5, rounded**2, rounded)
print(arr_less)

[ 2.5921  0.1681  0.5476  8.6    23.6196  2.7556  6.75    7.16    6.03
 10.89    8.41    5.41    5.08    9.98   17.3056 21.0681  8.77    9.71
  6.43    5.83  ]


Alternate sort

In [78]:
def numpy_alternate_sort(array):
  sorted = np.sort(array)
  result = []
  i,j = 0, len(sorted)-1
  while i <= j:
    result.append(sorted[i])
    if i != j:
      result.append(sorted[j])
      i += 1
      j -= 1
  return result

print(numpy_alternate_sort(rounded))

[np.float64(0.41), np.float64(9.98), np.float64(0.74), np.float64(9.71), np.float64(1.61), np.float64(8.77), np.float64(1.66), np.float64(8.6), np.float64(2.9), np.float64(7.16), np.float64(3.3), np.float64(6.75), np.float64(4.16), np.float64(6.43), np.float64(4.59), np.float64(6.03), np.float64(4.86), np.float64(5.83), np.float64(5.08), np.float64(5.41)]


# **Question 3**

In [79]:
import pandas as pd
import numpy as np

data = {
    'Name':[f'Student{i+1}' for i in range(10)],
    'Subject': np.random.choice(['Math', 'Science', 'English'], size=10),
    'Score': np.random.randint(50, 101, size=10),
    'Grade': ['']*10
}
df = pd.DataFrame(data)

Grades

In [80]:
def assign_grade(score):
  if score>= 90: return 'A'
  if score>= 80: return 'B'
  if score>= 70: return 'C'
  if score>= 60: return 'D'
  else: return 'F'
df['Grade'] = df['Score'].apply(assign_grade)
print(df)

        Name  Subject  Score Grade
0   Student1  English     77     C
1   Student2  English     70     C
2   Student3  Science     64     D
3   Student4     Math     56     F
4   Student5  English     70     C
5   Student6  English     66     D
6   Student7  Science     54     F
7   Student8  English     53     F
8   Student9     Math     97     A
9  Student10  Science     61     D


Sorted Dataframe

In [81]:
print(df.sort_values(by= 'Score', ascending=False))

        Name  Subject  Score Grade
8   Student9     Math     97     A
0   Student1  English     77     C
1   Student2  English     70     C
4   Student5  English     70     C
5   Student6  English     66     D
2   Student3  Science     64     D
9  Student10  Science     61     D
3   Student4     Math     56     F
6   Student7  Science     54     F
7   Student8  English     53     F


Average Score per subject

In [82]:
print(df.groupby('Subject')['Score'].mean())

Subject
English    67.200000
Math       76.500000
Science    59.666667
Name: Score, dtype: float64


Pandas Filter Pass

In [83]:
def pandas_filter_pass(dataframe):
  return dataframe[dataframe['Score'] >= 90]
print(pandas_filter_pass(df))

       Name Subject  Score Grade
8  Student9    Math     97     A


# **Question 4**

In [84]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


reviews = ['Great movie!' for _ in range(50)] + ['Terrible movie!' for _ in range(50)]
sentiments = ['positive'] * 50 + ['negative'] * 50
df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

CountVectorizer

In [85]:
vectorizer = CountVectorizer(max_features=300, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

train, test and model

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0


predict_review_sentiment function

In [87]:
def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    return model.predict(review_vec)[0]

print("Test prediction:", predict_review_sentiment(model, vectorizer, "I loved the plot!"))

Test prediction: negative


# **Question 5**

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score
feedback = ['This is good' for _ in range(50)] + ['This is bad' for _ in range(50)]
labels = ['good'] * 50 + ['bad'] * 50
df2 = pd.DataFrame({'Feedback': feedback, 'Label': labels})

Vectorization

In [89]:
vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(df2['Feedback'])
y = df2['Label']

Split

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

Model

In [91]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)

print("Precision:", precision_score(y_test, y_pred, pos_label='good'))
print("Recall:", recall_score(y_test, y_pred, pos_label='good'))
print("F1-Score:", f1_score(y_test, y_pred, pos_label='good'))


Precision: 1.0
Recall: 1.0
F1-Score: 1.0


text preprocess vectorize

In [92]:
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

# Example usage
print("Vectorized test sample:", text_preprocess_vectorize(["amazing product"], vectorizer).toarray())


Vectorized test sample: [[0. 0.]]
